language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

env:
    global:
        - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

matrix:
    include:
        - php: 7.1
          env: LARAVEL_VERSION=5.5.*
        - php: 7.1
          env: LARAVEL_VERSION=5.8.*
        - php: 7.2
          env: LARAVEL_VERSION=5.5.*
        - php: 7.2
          env: LARAVEL_VERSION=5.8.*
        - php: 7.2
          env: LARAVEL_VERSION=^6.0


        - php: 5.6
          env: SYMFONY_VERSION=3.3.*@dev
        - php: 5.6
          env: SYMFONY_VERSION=3.4.*@dev
        - php: 7.2
          env: SYMFONY_VERSION=4.0.*@dev
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest"


    fast_finish: true
    exclude:
        - php: 7.1
          env: LARAVEL_VERSION="^6.0" TESTBENCH_VERSION="^4.0" PHPUNIT_VERSION="^8.0"
    allow_failures:
        - php: 7.4snapshot

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - travis_retry composer self-update
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
    - travis_retry composer require "laravel/laravel:${LARAVEL_VERSION}"

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

branches:
    only:
        - master
